# SPRING PROPERTIES
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: local

server:
  error:
    include-message: always

bucket:
  region: "us-east-1"
  s3: "emoralesinvoice"
  path: "pdf"
  duration: '30'
  credentialId: 'AKIAWUQAQIKDNDBN4CLA'
  secretId: 'blsjD2LgXE5eYEpoZaBhK9dWeqreiXMflA4S8XE7'